export * from "./Agenda"
export * from "./InformeActividades"
export * from "./Transparencia"
export * from "./Error"
export * from "./Servicios"
export * from "./Evaluacion"
export * from "./Inicio"
export * from "./InformacionInstitucional"